// Operator signing CLI (DEC-0015): derived-identity signing with fail-closed
// path handling — in-repository keys, symlinks, and non-owner-only
// permissions are refused; a derived key_id that is not enrolled cannot sign;
// independent-review gates are refused outright; no private material reaches
// any output channel; and the produced evidence verifies and consumes exactly
// once. All keys are ephemeral, generated by the keygen CLI into temp
// directories — never the real Product Owner key.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { type TrustedAuthorityConfig, loadTrustedAuthorityConfig } from "../src/authority/authority.js";
import { FileApprovalReceiptStore } from "../src/authority/receipt-store.js";
import { verifyAndConsumeApproval } from "../src/authority/verify-approval.js";
import { FileArtifactStore } from "../src/kernel/artifact-store.js";
import { BRAND, WS, registry, repoRoot, tempDir, validClaim } from "./helpers.js";

const SIGN_CLI = join(repoRoot, "dist", "src", "cli", "sign-approval.js");
const KEYGEN_CLI = join(repoRoot, "dist", "src", "cli", "keygen.js");
const SUBJECT = "ibrahim-mohamed";

interface CliRun {
  status: number | null;
  stdout: string;
  stderr: string;
}

function run(cli: string, args: string[]): CliRun {
  const result = spawnSync(process.execPath, [cli, ...args], { encoding: "utf8" });
  return { status: result.status, stdout: result.stdout, stderr: result.stderr };
}

interface SigningScenario {
  privateKeyPath: string;
  candidate: Record<string, unknown>;
  configDir: string;
  artifactsRoot: string;
  evidenceDir: string;
}

/**
 * Ceremony-equivalent setup: an ephemeral keypair from the keygen CLI, an
 * isolated trusted-config directory mirroring the enrolled v2 shape, and a
 * temp artifact store holding one claim. A wide validity window keeps the
 * scenario independent of the host clock.
 */
function signingScenario(): SigningScenario {
  const keyDir = tempDir("signcli-keys");
  const privateKeyPath = join(keyDir, "private.pem");
  const candidatePath = join(keyDir, "candidate.json");
  const keygen = run(KEYGEN_CLI, [
    "--subject-id",
    SUBJECT,
    "--label",
    "Ephemeral signing-CLI test authority",
    "--roles",
    "product-owner",
    "--valid-from",
    "2020-01-01T00:00:00Z",
    "--private-key-out",
    privateKeyPath,
    "--public-candidate-out",
    candidatePath,
  ]);
  assert.equal(keygen.status, 0, `keygen must succeed: ${keygen.stderr}`);
  const candidate = JSON.parse(readFileSync(candidatePath, "utf8")) as Record<string, unknown>;

  const configDir = tempDir("signcli-config");
  const registryDocument = {
    schema_version: "1.9.0",
    registry_id: "areg-nabcor",
    registry_version: 2,
    supersedes_registry_version: 1,
    created_at: "2026-07-19T00:08:51Z",
    decision_ref: "DEC-0015",
    authorities: [candidate],
  };
  const policy = JSON.parse(
    readFileSync(join(repoRoot, "contracts", "human-gate-policy.active.json"), "utf8")
  ) as Record<string, unknown>;
  writeFileSync(
    join(configDir, "authority-registry.active.json"),
    JSON.stringify(registryDocument, null, 2) + "\n",
    "utf8"
  );
  writeFileSync(
    join(configDir, "human-gate-policy.active.json"),
    JSON.stringify(policy, null, 2) + "\n",
    "utf8"
  );

  const artifactsRoot = tempDir("signcli-artifacts");
  const store = new FileArtifactStore(artifactsRoot, registry());
  assert.ok(store.put(WS, BRAND, "claim", validClaim()).ok, "test setup: claim put failed");

  return { privateKeyPath, candidate, configDir, artifactsRoot, evidenceDir: tempDir("signcli-evidence") };
}

function signArgs(s: SigningScenario, overrides: Record<string, string> = {}): string[] {
  const flags: Record<string, string> = {
    "--private-key": s.privateKeyPath,
    "--artifacts-root": s.artifactsRoot,
    "--workspace": WS,
    "--brand-ref": BRAND,
    "--target-type": "claim",
    "--target-ref": "claim_t_0001",
    "--gate": "fact-resolution-approval",
    "--verdict": "approved",
    "--reason": "synthetic signing-CLI test approval",
    "--requester-id": SUBJECT,
    "--evidence-out": join(s.evidenceDir, "evidence.json"),
    "--trusted-config-dir": s.configDir,
    ...overrides,
  };
  return Object.entries(flags).flat();
}

test("the signing CLI produces contract-valid evidence with a derived identity that verifies and consumes exactly once, leaking no private material", () => {
  const s = signingScenario();
  const result = run(SIGN_CLI, signArgs(s));
  assert.equal(result.status, 0, `sign-approval must succeed: ${result.stderr}`);

  // No private material in any output channel or in the evidence itself.
  const pem = readFileSync(s.privateKeyPath, "utf8");
  const evidenceRaw = readFileSync(join(s.evidenceDir, "evidence.json"), "utf8");
  const armor = ["PRIVATE", "KEY"].join(" ");
  for (const channel of [result.stdout, result.stderr, evidenceRaw]) {
    assert.ok(!channel.includes(armor), "no PEM armor in any output");
    for (const line of pem.split("\n")) {
      if (line.length > 10 && !line.startsWith("-----")) {
        assert.ok(!channel.includes(line), "no private key body material in any output");
      }
    }
  }

  // The evidence is contract-valid and its identity fields are DERIVED from
  // the key and registry, not asserted by the operator.
  const evidence = JSON.parse(evidenceRaw) as Record<string, unknown>;
  const validated = registry().validate("approval-evidence", evidence);
  assert.ok(validated.ok, `evidence must be contract-valid: ${JSON.stringify(validated)}`);
  const payload = evidence["payload"] as Record<string, unknown>;
  assert.equal(payload["key_id"], s.candidate["key_id"], "key_id derives from the private key");
  assert.equal(payload["approver_id"], SUBJECT, "approver_id derives from the registry subject");
  assert.equal(payload["role"], "product-owner");
  assert.equal(payload["self_review"], true);
  assert.equal(payload["policy_ref"], "hgp-nabcor-1");
  assert.equal(payload["policy_version"], 3);

  // The evidence verifies and consumes exactly once against the same config.
  const loaded = loadTrustedAuthorityConfig(
    join(s.configDir, "human-gate-policy.active.json"),
    join(s.configDir, "authority-registry.active.json"),
    registry()
  );
  assert.ok(loaded.ok);
  const deps = {
    contracts: registry(),
    artifactStore: new FileArtifactStore(s.artifactsRoot, registry()),
    receiptStore: new FileApprovalReceiptStore(tempDir("signcli-receipts"), registry()),
    config: loaded.ok ? (loaded.value as TrustedAuthorityConfig) : (null as never),
    clock: () => new Date().toISOString(),
  };
  const first = verifyAndConsumeApproval(evidence, deps);
  assert.ok(first.ok, `CLI evidence must authorize: ${JSON.stringify(first)}`);
  const replay = verifyAndConsumeApproval(evidence, deps);
  assert.ok(!replay.ok, "replay must fail");
  assert.equal(replay.ok ? "" : replay.error.kind, "approval-replay");
});

test("the signing CLI refuses a private key inside the repository, before reading it", () => {
  const s = signingScenario();
  const inRepoKey = join(repoRoot, `tmp-signcli-test-${process.pid}.pem`);
  writeFileSync(inRepoKey, "not a real key\n", { mode: 0o600 });
  try {
    const result = run(SIGN_CLI, signArgs(s, { "--private-key": inRepoKey }));
    assert.equal(result.status, 1);
    assert.match(result.stderr, /inside the repository/);
    assert.ok(!existsSync(join(s.evidenceDir, "evidence.json")), "no evidence is written");
  } finally {
    unlinkSync(inRepoKey);
  }
});

test("the signing CLI refuses symlinked keys and non-owner-only permissions", () => {
  const s = signingScenario();
  const linkDir = tempDir("signcli-symlink");
  const linkedKey = join(linkDir, "linked.pem");
  symlinkSync(s.privateKeyPath, linkedKey);
  const viaSymlink = run(SIGN_CLI, signArgs(s, { "--private-key": linkedKey }));
  assert.equal(viaSymlink.status, 1);
  assert.match(viaSymlink.stderr, /symlink/);

  chmodSync(s.privateKeyPath, 0o644);
  const insecure = run(SIGN_CLI, signArgs(s));
  assert.equal(insecure.status, 1);
  assert.match(insecure.stderr, /owner-only/);
  assert.ok(!existsSync(join(s.evidenceDir, "evidence.json")), "no evidence is written");
});

test("the signing CLI rejects a private key whose derived key_id is not enrolled", () => {
  const s = signingScenario();
  const otherDir = tempDir("signcli-other-key");
  const otherKey = join(otherDir, "other.pem");
  const keygen = run(KEYGEN_CLI, [
    "--subject-id",
    SUBJECT,
    "--label",
    "Unenrolled ephemeral key",
    "--roles",
    "product-owner",
    "--valid-from",
    "2020-01-01T00:00:00Z",
    "--private-key-out",
    otherKey,
    "--public-candidate-out",
    join(otherDir, "candidate.json"),
  ]);
  assert.equal(keygen.status, 0);
  const result = run(SIGN_CLI, signArgs(s, { "--private-key": otherKey }));
  assert.equal(result.status, 1);
  assert.match(result.stderr, /not enrolled/);
  assert.ok(!existsSync(join(s.evidenceDir, "evidence.json")), "no evidence is written");
});

test("the signing CLI refuses every independent-review gate in the self-signing flow", () => {
  const s = signingScenario();
  for (const gate of [
    "quarantine-release",
    "client-facing-publishing",
    "blocking-evaluation-gate-change",
    "real-client-data-provider-approval",
  ]) {
    const result = run(SIGN_CLI, signArgs(s, { "--gate": gate }));
    assert.equal(result.status, 1, `gate '${gate}' must be refused`);
    assert.match(result.stderr, /independent/);
    assert.ok(!existsSync(join(s.evidenceDir, "evidence.json")), "no evidence is written");
  }
});

test("the signing CLI exclusive-creates its output, refuses in-repository evidence, and enforces the policy TTL ceiling", () => {
  const s = signingScenario();
  const evidencePath = join(s.evidenceDir, "evidence.json");
  writeFileSync(evidencePath, "already here", "utf8");
  const overwrite = run(SIGN_CLI, signArgs(s));
  assert.equal(overwrite.status, 1);
  assert.match(overwrite.stderr, /refusing to overwrite/);
  assert.equal(readFileSync(evidencePath, "utf8"), "already here", "existing file untouched");
  unlinkSync(evidencePath);

  const inRepo = run(SIGN_CLI, signArgs(s, { "--evidence-out": join(repoRoot, "tmp-evidence-never.json") }));
  assert.equal(inRepo.status, 1);
  assert.match(inRepo.stderr, /inside the repository/);
  assert.ok(!existsSync(join(repoRoot, "tmp-evidence-never.json")));

  const overTtl = run(SIGN_CLI, signArgs(s, { "--ttl-seconds": "999999" }));
  assert.equal(overTtl.status, 1);
  assert.match(overTtl.stderr, /exceeds the policy maximum/);

  const symDir = tempDir("signcli-evidence-symlink");
  const realDir = join(symDir, "real");
  mkdirSync(realDir);
  const linkedDir = join(symDir, "linked");
  symlinkSync(realDir, linkedDir);
  const viaSymlinkDir = run(SIGN_CLI, signArgs(s, { "--evidence-out": join(linkedDir, "evidence.json") }));
  assert.equal(viaSymlinkDir.status, 1);
  assert.match(viaSymlinkDir.stderr, /symlink/);
});

test("the signing CLI takes no identity or key material from environment variables", () => {
  // Structural guarantee: the CLI source never reads process.env — every
  // input is an explicit flag, and identity is derived from the key itself.
  const source = readFileSync(join(repoRoot, "src", "cli", "sign-approval.ts"), "utf8");
  assert.ok(!/process\.env/.test(source), "sign-approval.ts must not read environment variables");
  const keygenSource = readFileSync(join(repoRoot, "src", "cli", "keygen.ts"), "utf8");
  assert.ok(!/process\.env/.test(keygenSource), "keygen.ts must not read environment variables");
});
